### ISSUE TITLE
استفاده از کتابخانهwordpress-eloquent

### ISSUE THREAD

**Issue by 1mahdimf** [mehrshaddarzi/wp-trait#37]
سلام و وقت بخیر

نظرتون چیه کتابخونه زیر رو هم به هسته فریمورک اضافه کنید.

https://github.com/drewjbartlett/wordpress-eloquent

**Comment by mehrshaddarzi** [comment]
سلام
این پکیج در نسخه های آتی جز گزینه های کامند
trait add
قرار داده می شود.

https://github.com/mehrshaddarzi/wp-cli-trait-command/issues/1
