### ISSUE TITLE
post($id)->exists() bug

### ISSUE THREAD

**Issue by midweste** [mehrshaddarzi/wp-trait#45]
I was debugging an issue we had when using post exists.  For brevity:

```
$id = false;
$exists = $this->post($id)->exists();
```
This will return true.

Because get_post_status is provided with false as argument, it will load the $GLOBALS['post'] using get_post, so instead of checking if the post id specified exists, it checks if the current page global post exists (many times returning true)

```
        public function exists($post_id = null)
        {
            return is_string(get_post_status((is_null($post_id) ? $this->post_id : $post_id)));
        }
```

Will try to submit a pull request when I have a free moment

**Comment by mehrshaddarzi** [comment]
@midweste 
Thanks for your report,
