### ISSUE TITLE
Uncaught Error: Class "\WPTrait\Collection\Constant" not found

### ISSUE THREAD

**Issue by 1mahdimf** [mehrshaddarzi/wp-trait#55]
در بخش زیر کلاس های Globals و Constant اشتباه ادرس دهی شدن.

https://github.com/mehrshaddarzi/wp-trait/blob/f91d4a1e38ac78b7fa724cf1a1fe0ba8834e104d/src/Model.php#L113-L137

**Comment by mehrshaddarzi** [comment]
@1mahdimf 
We take Unit Test in Master Branch.
Use last release in your Project.
